### PR TITLE
Suggest how to participate anonymously

### PR DESCRIPTION
**Pull request by patcon**
As in, no name and no phone number.

Slack context: https://edgi.slack.com/archives/C4H23J40J/p1496763987320291

--------------------
EDIT: bringing over really amazing comments before slack archives disappear:

> **Alice:** love this idea to streamline the video flow, and you've done a great job in breaking down to essentials, and using tech to speed processes smartly. props to you! my only suggestion might be around that github landing page, letting people know how to participate anonymously, knowing that the call will be recorded / archived. [also, depends on your anonymous protocol as an org overall. reasons i might want to remain anon in recorded info: say i work for a government agency or 503(c) that is specifically non-partisan, and currently politicized/polarized, but want to participate as a private citizen, i may not want my name or phone number identified anywhere for safety / security. i know many people in this boat actually, who have to keep a very low profile in their activities: depends on how you want to approach.] take this suggestion as it makes sense for your use case.

> **Bob:** One possible improvement would be a bullet point as follows:
> > 5. If you wish to remain anonymous, please consider taking the following steps: Set up a Zoom account underan alias; keep your video turned off; do not connect via the telephone number listed in the announcement (though I guess the last point is a bit late for anyone who has dialed in by phone).

> **Alice:** re: dial in / telephone identification: does that get reflected on that disclaimer landing page, or is there an opp to abandon there? might be worth exploring

> **Bob:** If you have somehow found the telephone number (which, I'm now thinking, might be hard to do in this new system) then presumably it will connect you directly to the call without passing you through the landing page...
> ... which takes care of the "accidentally identifying yourself by phone number" problem -- so that's nice -- but makes it impossible for people to connect unless they have Internet access -- which is a pretty common situation for people to be in if they live in North America outside.

### CODE REVIEW

**Comment by patcon** [comment]
This is, for practical purposes, blocked by https://github.com/edgi-govdata-archiving/video-call-landing-page/issues/2

We could link docs on how to block caller id, but we can't list a number yet, so i feel it's just confusing...?

**Comment by patcon** [comment]
Converted this to a PR, but going to set up heroku review apps as part of this, so WIP

**Comment by patcon** [comment]
ok done, ready for review!

**Comment by patcon** [comment]
As referenced in the little "view deployment" link above, you can see sample landing page here:
https://edgi-video-call-landing-p-pr-1.herokuapp.com/https://zoom.us/j/508236833

**Review by dcwalk — APPROVED** [review]
Looks good, only thing I would say is it looks jarring to have the stylesheet only on the phone landing page but not on the explainer page (e.g., https://edgi-video-call-landing-p-pr-1.herokuapp.com/ for this review)

That to me is out of scope of this PR tho

**Comment by patcon** [comment]
Thanks! And good call! I'll open another ticket to keep track, but not expecting to work on it myself tbh :)

**Pull request merged**
